//WHAT HAVE I DONE? I THOUGHT SOFTWARE DEVELOPMENT IS EASY EH?
//FFS I THINK IT'S NOT
//I THINK IT'S NOT
//I THINK IT'S NOT
//HELP ME

//I DID THIS TO MYSELF
//I DID THIS TO MYSELF
//I DID THIS TO MYSELF
//I DID THIS TO MYSELF
//I DID THIS TO MYSELF
//I DID THIS TO MYSELF
//I DID THIS TO MYSELF
//I DID THIS TO MYSELF
//I DID THIS TO MYSELF
//I DID THIS TO MYSELF

//HELP I FEEL LIKE IM DYING!!!

require('./UserCreator').createUser('John', '1234567890', 'jonwick@wicked.com', 'password')


